Updated

diff --git a/MCProduction/pionGun/GEN-SIM-DIGI-RAW/qsub_PionGun_GEN-SIM-DIGI-RAW b/MCProduction/pionGun/GEN-SIM-DIGI-RAW/qsub_PionGun_GEN-SIM-DIGI-RAW
--- a/MCProduction/pionGun/GEN-SIM-DIGI-RAW/qsub_PionGun_GEN-SIM-DIGI-RAW
+++ b/MCProduction/pionGun/GEN-SIM-DIGI-RAW/qsub_PionGun_GEN-SIM-DIGI-RAW
@@ -7,7 +7,7 @@ set test = false
 eval `scram runtime -csh`
 
 ## User sets these run variables
-set package     = Producers/CaloTowersFromTrigPrimsCreator/pionGun/GEN-SIM-DIGI-RAW/
+set package     = MCProduction/pionGun/GEN-SIM-DIGI-RAW/
 set exec_name   = PionGun_GEN-SIM-DIGI-RAW
 set base_dir    = /uscmst1b_scratch/lpc1/3DayLifetime/${user}/
 set type        = PionGun
@@ -18,6 +18,7 @@ set condor_dir  = ${base_dir}/${type}/condor
 set log_dir     = ${base_dir}/${type}/log
 set output_dir  = ${base_dir}/${type}/output
 set exec_path   = ${CMSSW_BASE}/src/${package}/qrun_${exec_name}
+set tar_file    = Release.tar
 
 if ($test != true) then
 
@@ -48,6 +49,19 @@ endif
 ## If input doesn't make sense, print the usage and bail
 
 ## Check to make sure all of the executables and directories are where they should be
+
+if ( ! -e ${CMSSW_BASE}/src/${tar_file} ) then 
+    echo "Warning! No tar file for this release!" 
+    echo "Trying to create it..."
+    cd ${CMSSW_BASE}/src/
+    tar cf ${tar_file} *
+    if ( ! -e ${CMSSW_BASE}/src/${tar_file} ) then 
+	echo "Failed to create ${tar_file}. Exiting"
+	exit 1
+    endif
+    echo "OK"
+endif
+
 if (! -e ${condor_dir}) then 
     echo "Warning! Could not find condor directory ${condor_dir}"
     echo "Trying to create it..."
